function frisVelocityVec = frisbeeCOMVelocityVector_3DOF(l1,l2,l3,rfris,th1,th2,th3,th1dot,th2dot,th3dot,thFrisOrient)
%FRISBEECOMVELOCITYVECTOR_3DOF
%    FRISVELOCITYVEC = FRISBEECOMVELOCITYVECTOR_3DOF(L1,L2,L3,RFRIS,TH1,TH2,TH3,TH1DOT,TH2DOT,TH3DOT,THFRISORIENT)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    10-May-2021 14:00:42

t2 = th3+thFrisOrient;
frisVelocityVec = [-th3dot.*(l3.*sin(th3)+rfris.*sin(t2))-l1.*th1dot.*sin(th1)-l2.*th2dot.*sin(th2);th3dot.*(l3.*cos(th3)+rfris.*cos(t2))+l1.*th1dot.*cos(th1)+l2.*th2dot.*cos(th2)];
